add new line
EXXAI/exxai.github.io pull request #1
Opened 2018-10-19 12:45 UTC by oliverweisse

2018-10-19 12:47 UTC, waltherg commented on _posts/2018-10-18-sales-prediction.md
> +Let us have a look at what we want to predict: neues wort
Gefällt mir nicht

2018-10-19 12:48 UTC, waltherg commented on _posts/2018-10-18-sales-prediction.md
> +Let us have a look at what we want to predict: neues wort
```suggestion
Let us have a look at what we want to predict: neues wort
Let us have a look at what we want to predict:
```

2018-10-19 12:49 UTC, oliverweisse commented on _posts/2018-10-18-sales-prediction.md
> +Let us have a look at what we want to predict: neues wort
Warum nicht?

2018-10-23 09:25 UTC, waltherg requested changes

2018-10-23 09:25 UTC, waltherg commented on _posts/2018-10-18-sales-prediction.md
> +In the last years technologies like data science, artificial intelligence and predictive analytics have become
such as

2018-10-23 09:25 UTC, waltherg commented on _posts/2018-10-18-sales-prediction.md
> +increasingly popular. There are several applications of these technologies which include target marketing, churn
targeted marketing

2018-10-23 09:25 UTC, waltherg commented on _posts/2018-10-18-sales-prediction.md
> +nontechnical reader.
understood by nontechnical readers

2018-10-23 09:25 UTC, waltherg commented on _posts/2018-10-18-sales-prediction.md
> +On the platform “Kaggle.com” companies can upload their data and let data scientist compete to build the best machine
Beschreib hier direkt den verwendeten Datensatz und nicht Rossmann - ist sonst verwirrend

2018-10-23 09:25 UTC, waltherg commented on _posts/2018-10-18-sales-prediction.md
> +      <th>ID</th>
gibt dataframes ohne deren index aus

2018-10-23 09:25 UTC, waltherg commented on _posts/2018-10-18-sales-prediction.md
> +snippet of how our past sales data looks like:
have a look at ... a portion of our past sales data

2018-10-23 09:25 UTC, waltherg commented on _posts/2018-10-18-sales-prediction.md
> +Here, one row in the table is one transaction on a particular day. We also have the additional columns “date_block_num”
back ticks "`" statt "" geben besseres highlighting

2018-10-23 09:25 UTC, waltherg commented on _posts/2018-10-18-sales-prediction.md
> +At the moment, the data is not yet in the form, we want it to have. We want to predict the monthly sales for a
... the data is not yet in the format we need it in.

2018-10-23 09:25 UTC, waltherg commented on _posts/2018-10-18-sales-prediction.md
> +“item_cnt_day”. In data science jargon these transformations are called pivot tables or “groupbys”. It is part of the
are called pivot tables and group-bys

pivots und group-bys sind leicht unterschiedlich

2018-10-23 09:25 UTC, waltherg commented on _posts/2018-10-18-sales-prediction.md
> +“data wrangling process”: Transforming the raw data into the desired form. This part can take most of the data
keine ""

2018-10-23 09:25 UTC, waltherg commented on _posts/2018-10-18-sales-prediction.md
> +“data wrangling process”: Transforming the raw data into the desired form. This part can take most of the data
format

2018-10-23 09:25 UTC, waltherg commented on _posts/2018-10-18-sales-prediction.md
> +scientists time. After the transformation our data table looks like that:
scientist's

2018-10-23 09:25 UTC, waltherg commented on _posts/2018-10-18-sales-prediction.md
> +scientists time. After the transformation our data table looks like that:
looks as follows

2018-10-23 09:25 UTC, waltherg commented on _posts/2018-10-18-sales-prediction.md
> +For example, in June 2013, the item “482” was sold 2 times in shop 2. Let us now try to predict the sales of the next
"`" statt "" .. was sold two times in shop 2.

2018-10-23 09:25 UTC, waltherg commented on _posts/2018-10-18-sales-prediction.md
> +month without any machine learning. We will use the sales of the last month to predict the sales of this month. We have
previous month

2018-10-23 09:25 UTC, waltherg commented on _posts/2018-10-18-sales-prediction.md
> +month without any machine learning. We will use the sales of the last month to predict the sales of this month. We have
of the current month

2018-10-23 09:25 UTC, waltherg commented on _posts/2018-10-18-sales-prediction.md
> +points, we are four times off by 1 and one time off by 2. So,
we are off four times by one item sold and once by two items

2018-10-23 09:25 UTC, waltherg commented on _posts/2018-10-18-sales-prediction.md
> +points, we are four times off by 1 and one time off by 2. So,
Hence our measure of error is computed as follows

2018-10-23 09:25 UTC, waltherg commented on _posts/2018-10-18-sales-prediction.md
> +In practice we use the RMSE (root mean squared error). Instead of using the absolute deviation as above, we square the
root mean squared error (RMSE)

2018-10-23 09:25 UTC, waltherg commented on _posts/2018-10-18-sales-prediction.md
> +Now we know how good our predictions are. The lower the RMSE, the better. There are some commonly used error functions
Now we know how good our predictions are: the lower the RMSE, the more accurate our predictions are.

2018-10-23 09:25 UTC, waltherg commented on _posts/2018-10-18-sales-prediction.md
> +(also called “loss function”) like RMSE, but in practice it can be anything. For example, it could be how much money you
There are commonly used error functions (or loss functions) such as the RMSE we used above - but in practice we are free to design our own error function depending on our goal.

For instance we could choose our revenue as loss function - in case we manage to link our observed data to revenue - and maximize it.

2018-10-23 09:25 UTC, waltherg commented on _posts/2018-10-18-sales-prediction.md
> +make if you can make a connection between the data science problem and your finances. In the data science practice, the
In data science practice

2018-10-23 09:25 UTC, waltherg commented on _posts/2018-10-18-sales-prediction.md
> +complete last month that we have the true sales data for, we obtain a RMSE of
obtain an RMSE of

2018-10-23 09:25 UTC, waltherg commented on _posts/2018-10-18-sales-prediction.md
> +complete last month that we have the true sales data for, we obtain a RMSE of
der Wert des RMSE fehlt hier noch

2018-10-23 09:25 UTC, waltherg commented on _posts/2018-10-18-sales-prediction.md
> +path down. The item count two months ago was also 0. Again, we go down the left path and we predict the value 0.3. This
Since ..., coming from the top of the tree we go left as we continue downwards where we predict an amount sold of 0.3.

2018-10-23 09:25 UTC, waltherg commented on _posts/2018-10-18-sales-prediction.md
> +decision tree, we obtain a RMSE of . This is better than just predicting the last month’s item count.
we obtain an RMSE of ...

Wert fehlt

2018-10-23 09:25 UTC, waltherg commented on _posts/2018-10-18-sales-prediction.md
> +The decision tree is created in that way that the error function (RMSE) is minimized. It is important to note that we
The machine learning algorithm we use created the tree in such a manner as to minimize the RMSE on our historical data.

2018-10-23 09:25 UTC, waltherg commented on _posts/2018-10-18-sales-prediction.md
> +cannot test our model on the same data that our decision tree was trained on. Our decision tree was created with data
Training and evaluating our tree on the same data set does not provide any insight as to how well our tree will predict sales in the future - or how well our tree generalizes.

2018-10-23 09:25 UTC, waltherg commented on _posts/2018-10-18-sales-prediction.md
> +from month 1-4 in that way that the RMSE is small on these particular months. The RMSE error that really counts is the
from months 1 - 4 (January through April) such that the RMSE is minimal for those months.

2018-10-23 09:25 UTC, waltherg commented on _posts/2018-10-18-sales-prediction.md
> +from month 1-4 in that way that the RMSE is small on these particular months. The RMSE error that really counts is the
The RMSE that

error doppelt

2018-10-23 09:25 UTC, waltherg commented on _posts/2018-10-18-sales-prediction.md
> +RMSE on month 5 that the algorithm has not seen yet. Otherwise, we could build an extremely large tree that would
RMSE in month 5 (May)

2018-10-23 09:25 UTC, waltherg commented on _posts/2018-10-18-sales-prediction.md
> +perfectly predict the sales on month 1-4 but would be useless on month 5 because in interpreted too much into the data
be useless for predicting sales in month 5 / May

2018-10-23 09:25 UTC, waltherg commented on _posts/2018-10-18-sales-prediction.md
> +year’s exam in university or high school. If this year’s exam is the same as last year’s than your answers would be
then

2018-10-23 09:25 UTC, waltherg commented on _posts/2018-10-18-sales-prediction.md
> +understand the material so that you generalize well.
in order to generalize well.

2018-10-23 09:25 UTC, waltherg commented on _posts/2018-10-18-sales-prediction.md
> +The decision tree is very intuitive and also has the advantage that we can get an insight into which feature is the most
Decision trees are

2018-10-23 09:25 UTC, waltherg commented on _posts/2018-10-18-sales-prediction.md
> +understand. Fortunately, there are other methods which show us how important a feature is. In the next table you see the
to interpret.

2018-10-23 09:25 UTC, waltherg commented on _posts/2018-10-18-sales-prediction.md
> +This is, of course, a simplified version. In the Rossmann store challenge a lot more variables were given in the data.
besprich die eigentlich Daten nicht Rossmann

2018-10-23 09:25 UTC, waltherg commented on _posts/2018-10-18-sales-prediction.md
> +weather it was.
or prevailing weather conditions at the time.

2018-10-24 12:18 UTC, waltherg approved these changes

2018-10-24 12:18 UTC, merged